import images from "./images";
import icons from "./icons";
import { COLORS, FONT, SIZES, SHADOWS } from "./theme";
import { ROLES, COLLECTIONS, CATEGORIES, MENU_CATEGORIES, INGREDIENT_CLASSIFICATIONS, GOOGLE_MAP_API_KEY, GOOGLE_MAP_CONFIG } from './variables';

export { images, icons, COLORS, FONT, SIZES, SHADOWS, ROLES, COLLECTIONS, CATEGORIES, MENU_CATEGORIES, INGREDIENT_CLASSIFICATIONS, GOOGLE_MAP_API_KEY, GOOGLE_MAP_CONFIG };
